### ISSUE TITLE
How to calculate the FPR and MAE?

### ISSUE THREAD

**Issue by Mactor2018** [Dong-Huo/RGB-T-Glass-Segmentation#3]
Hello, thanks for your excellent work! I am working on the two metrics of images without glass, False Positive Rate (FPR) and Mean Absolute Error (MAE).
I learnt that 
$$MAE=\frac{1}{N}\sum\limits_{i=1}^{N}|P_i - G_i|$$.
When the GT is image without glass, $G$ is a zero matrix,
$$MAE=\frac{1}{N}\sum\limits_{i=1}^{N}|P_i - 0| =\frac{1}{N}\sum\limits_{i=1}^{N}P_i  $$
And since there's **no pixels of which GT=1**, then  the total number of pixels predicted as foreground is equal to the number of false positive pixels (FP), i.e.
$$MAE = \frac{FP}{N}$$

For False Positive Rate, 
$$FPR = \frac{FP}{N}$$

Hence it seems that **FPR=MAE** when no glass is in the image. 
But in your paper, they are not equivalent. Could you help me calculate them?

**Comment by Dong-Huo** [comment]
Hello, Thank you for your interest in our work. As mentioned in the paper,  FPR is calculated as the ratio of the number of false positives (i.e., glass are wrongly detected) to the total number of images without glass. It is an image level evaluation not pixel level.

**Comment by Mactor2018** [comment]
> Hello, Thank you for your interest in our work. As mentioned in the paper, FPR is calculated as the ratio of the number of false positives (i.e., glass are wrongly detected) to the total number of images without glass. It is an image level evaluation not pixel level.

So FPR equals the number of false positive **images** dividing the total number of **images** without glass?

Could you release the metrics code at your convenience?
